### ISSUE TITLE
Database outside of volume

### ISSUE THREAD

**Issue by evialle** [feedsbrain/instabot-docker#4]
Hello,

When executing the Docker image, the sqlite.db file isn't in /app/db but in /app/

Eg:
root@4d33c0c2cd2c:/app# ls
Dockerfile         README.md  db                   requirements  setup.py           tests
ISSUE_TEMPLATE.md  config     instabot.config.yml  session       sqlite.db          tox.ini
LICENSE            data       instabot_py          setup.cfg     start-instabot.py  version.txt

Here's the docker-compose file:
version: '3'

services:
  instabot: # recomended to use your username
    image: feedsbrain/instabot:1.3.5
    stdin_open: true
    tty: true
    restart: always
    environment:
      - IG_USER=******
      - IG_PASSWORD=*******
    volumes:
      - ./data:/app/data
      - ./session:/app/session
      - ./config:/app/config

**Comment by feedsbrain** [comment]
Hi, thank you for raising this issue. I will look into this, the database was meant to be under `db` folder and the filename should match your `username.db`.

**Comment by feedsbrain** [comment]
Hi @evialle 

I've merged the fix for this issue and released `Version 1.3.6` that includes this fix. You may need to copy the database to the proper name and location.

**Comment by Zzo911** [comment]
Hi,

With the latest version of the docker file, the db file is still not created under /app/db nor in /app.
So the bot new unlikes/unfollows.

Regards
